
-- mysql/mariadb

CREATE DATABASE IF NOT EXISTS example2;

CREATE TABLE IF NOT EXISTS example2.table2 (
  sn VARCHAR(255) PRIMARY KEY NOT NULL,
  name VARCHAR(255),
  description LONGTEXT,
  value DECIMAL(15,2),
  picture LONGBLOB,
  json JSON,
  note TEXT,
  created DATETIME DEFAULT CURRENT_TIMESTAMP,
  modified DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FULLTEXT(name, description, note),
  CHECK(VALID_JSON(json))
) ENGINE=InnoDB;



